### ISSUE TITLE
Change Column in COBie xlsx Attribute

### ISSUE THREAD

**Issue by simiii** [xBimTeam/XbimCobieExpress#14]
I use the IfcToCoBieExpressExchanger to convert an IFC file into COBie xlsx.
```
var cobie = new CobieModel();
using (var txn = cobie.BeginTransaction("begin conversion"))
{
	var exchanger = new IfcToCoBieExpressExchanger(model, cobie, null, null, null, EntityIdentifierMode.GloballyUniqueIds, SystemExtractionMode.System);
	exchanger.Convert();
	cobieModels.Add(cobie);
	txn.Commit();
}
```

In the exported COBie-Spreadsheet the columns in the Attribute sheet are in the following order:

Name | Category | CreatedBy | CreatedOn | SheetName | RowName | Value | Unit | ExtSystem | ExtObject | ExtIdentifier | Description | AllowedValues

First question: Is the order correct? Or must category come after createdOn?
Second question: Is it possible to change the order of the attribute columns?

Thanks in advance,
Simon

**Comment by martin1cerny** [comment]
I guess you have found there is a [configuration file](https://github.com/xBimTeam/XbimCobieExpress/blob/master/Xbim.IO.CobieExpress/Configurations/COBieUK2012.xml) where you can change the structure of the resulting sheet in any way you want.
