### ISSUE TITLE
Read a cobielite xml file

### ISSUE THREAD

**Issue by Thomas-E-A** [xBimTeam/XbimCobieExpress#8]
I have to read a cobielite file (xml). I cant find any example how to read this into a model.
I tried using the NuGet packages Xbim.CobieExpress and XbimExchanger.
Where can I find sample code?

**Comment by andyward** [comment]
Have you had a look over at the Exchange repo (where the CobieLite implementation is)?

https://github.com/xBimTeam/XbimExchange/blob/master/Tests/COBieLiteTests.cs
