### ISSUE TITLE
How to View Cobie file in viewer as same like Ifc file?

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimCobieExpress#9]
I have developed ifc file viewer based on xbim.
At same way i need to view the Cobie file..
What are the procedures have to make?please help to here. :)

**Comment by andyward** [comment]
There's no quick wins here. It depends on the use case, your tech stack (Windows/Web?), and your skill levels / budget.

**Comment by castronelson** [comment]
I have using web application

**Comment by andyward** [comment]
Definitely no quick answer then - it depends on what you want to do. As you may be finding out, the geometry is the simpler half of the problem managing BIM on the web. There's nothing in the toolkit to solve this beyond the [xBrowser](http://docs.xbim.net/XbimWebUI/xBrowser.html) code which views CobieLite Json.  We do have some (commercial) solutions to make this problem easier
